I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    define n_nvl = Character("Nighten", kind=nvl, image="nighten", callback=Discord_Ping)
  File "game/script.rpy", line 8, in <module>
    define n_nvl = Character("Nighten", kind=nvl, image="nighten", callback=Discord_Ping)
NameError: name 'Discord_Ping' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script
    define n_nvl = Character("Nighten", kind=nvl, image="nighten", callback=Discord_Ping)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/ast.py", line 2219, in execute
    self.set()
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/ast.py", line 2233, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 8, in <module>
    define n_nvl = Character("Nighten", kind=nvl, image="nighten", callback=Discord_Ping)
NameError: name 'Discord_Ping' is not defined

macOS-13.5.2-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Discord In Your Heart 1.0
Sat Feb 17 08:06:42 2024
