I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 78, in script
    with fade (0.6)
TypeError: 'MultipleTransition' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 78, in script
    with fade (0.6)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\display\core.py", line 2604, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\display\core.py", line 2518, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'MultipleTransition' object is not callable

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Discord In Your Heart 1.0
Sat Feb 17 14:37:53 2024
