I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "game/screens.rpy", line 267, in execute_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/main.py", line 635, in main
    run(restart)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/main.py", line 145, in run
    renpy.execution.run_context(True)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/exports.py", line 4090, in execute_default_statement
    i.execute_default(start)
  File "game/screens.rpy", line 267, in execute_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

macOS-13.5.2-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Discord In Your Heart 1.0
Sun Feb 18 11:07:59 2024
